### ISSUE TITLE
[SOZO] Migrate manifest.json to yaml manifests

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#1231]
The current manifest JSON file is a single, large file that contains all the information about contracts and classes. This makes it difficult to manage, especially when the number of contracts and classes increases and is changed over time.

```json
{
  "name": "actions",
  "address": null,
  "class_hash": "(...redacted...)",
  "abi": [
    {
      "type": "impl",
      "name": "WorldProviderImpl",
      "interface_name": "dojo::world::IWorldProvider"
    },
    // ... more items ...
  ],
  "reads": ["Moves", "Position"],
  "writes": ["Moves", "Position"],
  "computed": [
    {
      "contract": "actions",
      "entrypoint": "tile_terrain",
      "model": null
    },
    // ... more items ...
  ]
}
```

I propose to refactor the manifest JSON into multiple YAML files, similar to Kubernetes manifests. Each contract or class will have its own YAML file. This will make it easier to manage individual contracts and classes, will improve readability, and allow for future functionality like constructors. In contrast to the existing manifest system, the new approach will expect that manifests are committed to a projects repo and serve as a declarative offchain representation of the world.

Manifests will exist in two forms, `base` and `overlays`:

During compilation, when running `sozo build`, `base` manifests will be outputted by the compiler. For each model / contract, a manifest will be created for the class if it doesn't already exist or be updated if it does:

> Note: the abi property of each contract will point to an external *.abi file rather than embed it. We will need to update the compiler plugin to write these to disk.

Model:
```yaml
kind: model
name: world
path: dojo::world::world
class_hash: (...redacted...)
abi: example_model.abi
# ... other properties ...
```

Contract Class
```
kind: class
name: actions
path: dojo_examples::actions::actions
# https://book.dojoengine.org/cairo/metadata.html
metadata:
  name: Actions Contract
  ... 
class_hash: (...redacted...)
abi: actions.abi
dependencies:
  read:
    - Moves
    - Position
  write:
    - Moves
    - Position
computed:
  - contract: actions
    entrypoint: tile_terrain
    model: null
  # ... more items ...
```

Base manifests serve as a declarative representation of the current code base without deployment context. These configurations can be modified manually to include attributes such as permission configurations or constructor calldata.

During migration, `base` contracts are overlayed with deployment context. In the case of contracts, the `class` is converted into a `contract` with the associated deployment context, i.e. it's address:

Contract Instance
```
kind: contract
name: actions
path: dojo_examples::actions::actions
# https://book.dojoengine.org/cairo/metadata.html
metadata:
  name: Actions Contract
  ... 
address: 0xdead
class_hash: (...redacted...)
abi: actions.abi
dependencies:
  read:
    - Moves
    - Position
  write:
    - Moves
    - Position
computed:
  - contract: actions
    entrypoint: tile_terrain
    model: null
  # ... more items ...
```

The manifests are outputted into a `deployments/<chain id>` folder along with a chain configuration file with info such as rpc.

Running `build` and `migrate` is additive. It should modify the manifests in place if they already exist.
