### ISSUE TITLE
feat: Allow felt252 short strings on init_calldata

### ISSUE THREAD

**Issue by rsodre** [dojoengine/dojo#2587]
**Is your feature request related to a problem? Please describe.**

Currently, we can pass only numbers and addresses to `dojo_init()` through a profile config `init_calldata`.

Would be good to allow felt252 short strings.

EVEN BETTER: make it generic enough and accept anything, like `sozo --calldata`

**Describe the solution you'd like**

Use `sozo execute` prefixes to format `init_calldata`

```
$ sozo execute --help
  -c, --calldata <CALLDATA>
          The calldata to be passed to the system. Comma separated values e.g., 0x12345,128,u256:9999999999. Sozo supports some prefixes that you can use to automatically parse some types. The supported prefixes are:
                            - u256: A 256-bit unsigned integer.
                            - sstr: A cairo short string.
                            - str: A cairo string (ByteArray).
                            - int: A signed integer.
                            - no prefix: A cairo felt or any type that fit into one felt.
````

**Describe alternatives you've considered**

None

**Additional context**

A good usage example for short strings (and why I need it) is to pass `base_uri` to an ERC-721 token contract.

```toml
# sepolia profile
init_calldata = [
  "sstr:https://testnet.pistols.gg", # base_uri
]

# mainnet profile
init_calldata = [
  "sstr:https://play.pistols.gg", # base_uri
]

```
