### ISSUE TITLE
[BUG] Torii GraphQL Query Unexpected JSON EOF

### ISSUE THREAD

**Issue by Nami-Webisoft** [dojoengine/dojo#3040]
**Description**

When **querying** some models registered onto a deployed dojo world (katana and sepolia) containing u256 nested arrays inside **structs**, the user will receive this error in the graphql playground.

```graphql
"errors": [
    {
      "message": "Unexpected end of JSON input",
      "stack": "SyntaxError: Unexpected end of JSON input"
    }
  ]
```

Note, this issue has been reproduced with versions **v1.0.12** to **v1.2.0**.

**To Reproduce**

Build and deploy any dojo world with at least one model that contains an array of one or more `u256`s. Then, write the model in the dojo world at any point in your systems. Finally, upon successful writing of the model, query it in the graphql playground.

Example:

*models.cairo*

```rust
#[derive(Copy, Drop, Serde, Debug, Introspect)]
pub struct Struct256 {
    pub m_number: u256
}

#[derive(Drop, Serde, Debug)]
#[dojo::model]
pub struct TestModel {
    #[key]
    pub player: ContractAddress,
    pub m_struct: Array<Struct256>
}
```

*systems/actions.cairo*:

```rust
fn test(ref self: ContractState) {
      // Get the default world.
      let mut world = self.world_default();

      let mut test_model: TestModel = world.read_model(get_caller_address());
      let mut array: Array<Struct256> = array![Struct256 { m_number: u256 { high: 0, low: 0 } }];

      test_model.m_struct = array;
      world.write_model(@test_model);
  }
```

For simplicity sake, this example uses `dojo_starter` and will use localhost for katana as the rpc at `localhost:5050` and host torii locally at `localhost:8080`:

*Scarb.toml*:

```toml
[package]
cairo-version = "=2.9.2"
name = "dojo_starter"
version = "1.1.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate"                      # scarb run migrate
spawn = "sozo execute dojo_starter-actions spawn --wait"    # scarb run spawn
move = "sozo execute dojo_starter-actions move -c 1 --wait" # scarb run move

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.2.0" }

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[dev-dependencies]
cairo_test = "=2.9.2"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.2.0" }
```

*dojo_dev.toml*:

```toml
[world]
name = "Dojo starter"
description = "The official Dojo Starter guide, the quickest and most streamlined way to get your Dojo Autonomous World up and running. This guide will assist you with the initial setup, from cloning the repository to deploying your world."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/dojo-starter"
seed = "dojo_starter-v3"

[world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"

[namespace]
default = "dojo_starter"

[env]
rpc_url = "http://localhost:5050/"
# Default account for katana with seed = 0
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
# world_address = "0x06171ed98331e849d6084bf2b3e3186a7ddf35574dd68cab4691053ee8ab69d7"

[writers]
"dojo_starter" = ["dojo_starter-actions"]
```

*Sozo setup*:

```bash
sozo build --profile dev
sozo migrate --profile dev

sozo execute --profile dev actions test
```

*GraphQL Playground Input*:

Input:

```graphql
query test {
  dojoStarterTestModelModels {
    totalCount
      edges {
        node {
          m_struct {
            m_number
          }
        }
      }
   }
}
```

**Expected behavior**
The graphQL query should return an error with an `unexpected EOF` along with an `GraphQL proxy error: HyperError(hyper::Error(IncompleteMessage))` error logged where the torii instance is being hosted. 

```graphql
"errors": [
    {
      "message": "Unexpected end of JSON input",
      "stack": "SyntaxError: Unexpected end of JSON input"
    }
  ]
```

Note, that this does NOT happen if the model is registered but **does not have any associated data to it**. AKA, does not have any entities tied to it yet (totalCount = 0):

```graphql
"data": {
    "dojoStarterTestModelModels": {
      "totalCount": 0,
      "edges": []
    }
  }
```

Here's the error shown in the terminal where torii is being ran:

![Image](https://github.com/user-attachments/assets/0726d8e2-b387-452f-bbb7-4720f12254b8)

Here's the culprit in the source code in *torri/graphql/src/query/mod.rs*:

![Image](https://github.com/user-attachments/assets/ed0ae8ae-54eb-4bf0-9f5b-c8d8536a7a2b)

Here it panics due to unwraping a `None` value.

**Potential Solution**

I've tempered with the graphQL query rust source code for Torii and added a check to prevent unwraping on a None value:

![Image](https://github.com/user-attachments/assets/106b8ec9-7c26-4a11-86c4-84881f6a42ca)

I am unsure if this is the right move, but upon doing so and compiling the modified Torii and running it with the same world hash containing the setup, here's the output:

![Image](https://github.com/user-attachments/assets/6175549f-8ce5-41e3-be56-bb34d3f960e9)
