### ISSUE TITLE
Extend Scarb manifest for extracting Dojo metadata

### ISSUE THREAD

**Issue by kariy** [dojoengine/dojo#697]
Dojo allows user to specify Dojo-related metadata like `env`, in `Scarb.toml`, which would be used during the migration process or in other `sozo` commands.

Example `Scarbl.toml` :
```toml
[tool.dojo.env]
rpc_url = "http://localhost:5050/"

# Default account for katana with seed = 0
account_address = "0x03ee9e18edc71a6df30ac3aca2e0b02a198fbce19b7480a63a0d71cbd76652e0"
private_key = "0x0300001800000000300000180000000000030000000000003006001800006600"
```

Currently, Dojo metadata is extracted from the manifest file like so:

https://github.com/dojoengine/dojo/blob/309b76e0b929fc6d6edbb369fe26de70b56f23a0/crates/sozo/src/commands/options/mod.rs#L8-L10

And then, in `sozo` commands, the `env` table is extracted.

https://github.com/dojoengine/dojo/blob/309b76e0b929fc6d6edbb369fe26de70b56f23a0/crates/sozo/src/commands/component.rs#L73-L79

As you can see, this logic is repeated for every other commands that utilize the `env` metadata.

We can, however, make this process much cleaner by having something like below, where we can also have a proper struct for Dojo metadata.

```rust
use scarb::core::manifest::ManifestMetadata;

struct DojoMetadata {
   env: DojoEnv
}

impl MetadataExt for ManifestMetadata {
   fn dojo_metadata(&self) -> DojoMetadata {
      ... 
   }
}
```
